[package]
name = "esdt-nft-marketplace-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2018"
publish = false
[dependencies.esdt-nft-marketplace]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.4"
